name: Deployment of display software

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - 'display/**'
    - '.github/workflows/weatherboard-display-deploy.yml'
    - '!display/*.md'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: "Push to server"
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "display/"
          strip_components: 1
          target: "/home/${{ secrets.SSH_USERNAME }}/apps/weatherboard"
