name: Trigger auto deployment for weatherboard-api-ca

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - 'server/**'
    - '.github/workflows/weatherboard-api-ca-AutoDeployTrigger-8c7d7903-410b-4bc8-a86f-65d3d5b21a52.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.WEATHERBOARDAPICA_REGISTRY_USERNAME }}
          password: ${{ secrets.WEATHERBOARDAPICA_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: svopper/weatherboard-api-ca:${{ github.sha }}
          file: server/Dockerfile
          context: server/


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.WEATHERBOARDAPICA_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n weatherboard-api-ca -g weatherforecast-rg --server docker.io --username  ${{ secrets.WEATHERBOARDAPICA_REGISTRY_USERNAME }} --password ${{ secrets.WEATHERBOARDAPICA_REGISTRY_PASSWORD }}
            az containerapp update -n weatherboard-api-ca -g weatherforecast-rg --image svopper/weatherboard-api-ca:${{ github.sha }}
